name: pr-follow-up.yml

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  pr-follow-up:
    runs-on: ubuntu-latest
    steps:
      - name: Mark PR as Ready for Review
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              draft: false
            });
